language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: ygQCq0mj7dXDUOb0FjSn2i2BjpDbUi6WcMjl1i6dYwg9597jJvWGyHWuybq3MJ4yU5KHIdX8cCM2zuIiTC/Tul9p6XmQvSsv03FG58ey5q+GHaQ4WTznaQ8ECPreUcIAUhNY3o3p0r+QIE0+MSiwA6xsuCoaTi6w8X8lM7x5zTUaC2ZvGn83h4IZkww4rSV+M8w0LiLHpfUnZrn2ULynBOfcb2SD9w/xifk75BWFLza+EouwHbC/7yR1zs6+Q/p71Tv6pevDkD4NLC2rvV46wGe60h/A9dl3dZtxgbYNump6hyvwsA7WoPU0FkM23qnl2ICxH6aD91SdJoblhF4un/XuRrWzeXmn6tE7dMc7g8iLUzKZGIDbkibQJ3p8U1D5lDOplLwJumKXbsSaRbZ6H0q+15SqnnqobIbhiq9jzB7GQQYU91B/gwiRXyLaSPdn+SPMXyOksfu7nUAe9+nNc0gjSVEyED/8Qk3lWEutvXNhh/dKENL4UdZ9XN3k8jNv17dfO6JzSnaeFXjJdaAieAUQNFCluJXYjOEjUHZuKonvPBBiGOd4+753pN1Ml1ARrsfpLL4vzMSpyjbJ717xtQ4dbg2BeOPuM9675uCGGtz4eyBwsPDDo3aShJdpjmCkQG+oR0Z13OHEIBrdqC3s8lsBEpV6f3qhPDYOj5Hejnw=
  file: build/libs/tinycards-importer-1.0-SNAPSHOT.jar
  on:
    repo: jjedele/duolingo-tinycards-importer
